### ISSUE TITLE
Plone 6: remove hard dependency on Archetypes

### ISSUE THREAD

**Issue by Rudd-O** [collective/sc.social.like#186]
```
Got sc.social.like 2.13.
Getting distribution for 'Products.CMFQuickInstallerTool'.
Got Products.CMFQuickInstallerTool 4.0.4.
Getting distribution for 'Products.Archetypes'.
WARNING: The easy_install command is deprecated and will be removed in a future version.
Traceback (most recent call last):
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-cnx54p1z/Products.Archetypes-1.16.6/setup.py", line 8, in <module>
ValueError: Archetypes is Python 2 only.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 2317, in main
    setup(
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/user/optpython/3.8.6/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/user/optpython/3.8.6/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/user/optpython/3.8.6/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/user/optpython/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/optpython/3.8.6/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/user/optpython/3.8.6/lib/python3.8/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-cnx54p1z/Products.Archetypes-1.16.6/setup.py", line 8, in <module>
ValueError: Archetypes is Python 2 only.
```

**Comment by Rudd-O** [comment]
Fixed by https://github.com/collective/sc.social.like/pull/187 .
